# Collect Data from Files
In this case study, we are going to collect weather data from all kinds of sources. At the end, we will have an integrated csv file for further analysis in next courses.

In [1]:
import pandas as pd

## Colunms
This is a simplified scenario, is that we know the data are following same structure. We don't have to worry about the order of columns.

In real life scenario, we may have to investigate and find out how columns across different resources. 
1.   Are they the same or different? 
1.   If they share the same name, do they represent the same attribute? For example, `price` in source 1, and `price` in source 2. How about `price` in source 1 is in US Dollars, and `price` in source 2 is in EURO?
1.   If they have different names, do they really represent different attributes? For example, `DoB` in source 1 and `Birthday` in source 2. `STUID` in source 1 and `ID` in source 2.

## TXT

In [2]:
df1 = pd.read_csv('Data/boulderdaily_Part1.txt')
df1

      year  month  day  tmax  tmin  precip   snow  snowcover
0     1897      1    1  -998  -998  -998.0 -998.0       -998
1     1897      1    2  -998  -998  -998.0 -998.0       -998
2     1897      1    3  -998  -998  -998.0 -998.0       -998
3     1897      1    4  -998  -998  -998.0 -998.0       -998
4     1897      1    5  -998  -998  -998.0 -998.0       -998
...    ...    ...  ...   ...   ...     ...    ...        ...
1093  1899     12   27    50    22     0.0 -998.0       -998
1094  1899     12   28    43    23     0.0 -998.0       -998
1095  1899     12   29    56    23     0.0 -998.0       -998
1096  1899     12   30    48    24     0.0 -998.0       -998
1097  1899     12   31    50    25     0.0 -998.0       -998

[1098 rows x 8 columns]

## Excel

In [5]:
df2 = pd.read_excel('Data/boulderdaily_Part2.xlsx')
df2

       year  month  day  tmax  tmin  precip  snow  snowcover
0      1900      1    1    40    18     0.0  -998       -998
1      1900      1    2    47    20     0.0  -998       -998
2      1900      1    3    57    31     0.0  -998       -998
3      1900      1    4    47    33     0.0  -998       -998
4      1900      1    5    53    29     0.0  -998       -998
...     ...    ...  ...   ...   ...     ...   ...        ...
10975  1929     12   27    49    24     0.0  -998       -998
10976  1929     12   28    59    19     0.0  -998       -998
10977  1929     12   29    61    31     0.0  -998       -998
10978  1929     12   30    62    36     0.0  -998       -998
10979  1929     12   31    55    32     0.0  -998       -998

[10980 rows x 8 columns]

## HTML

In [6]:
df3 = pd.read_html('Data/boulderdaily_Part3.html', header = 0)[0]
df3

      year  month  day  tmax  tmin  precip  snow  snowcover
0     1930      1    1    45    20 -999.00  -998       -998
1     1930      1    2    36    17    0.01  -998       -998
2     1930      1    3    54    13    0.00  -998       -998
3     1930      1    4    57    26    0.00  -998       -998
4     1930      1    5    58    28    0.00  -998       -998
...    ...    ...  ...   ...   ...     ...   ...        ...
3655  1939     12   27    21     2    0.12  -998       -998
3656  1939     12   28    45    14    0.00  -998       -998
3657  1939     12   29    49    26    0.00  -998       -998
3658  1939     12   30    57    36    0.00  -998       -998
3659  1939     12   31    47    24 -999.00  -998       -998

[3660 rows x 8 columns]

## json

In [7]:
df4 = pd.read_json('Data/boulderdaily_Part4.json')
df4

      year  month  day  tmax  tmin  precip   snow  snowcover
0     1940      1    1    28    20 -999.00 -998.0       -998
1     1940      1    2    44    20    0.00 -998.0       -998
2     1940      1    3    34    27 -999.00 -998.0       -998
3     1940      1    4    28    18    0.10 -998.0       -998
4     1940      1    5    22     5    0.31 -998.0       -998
...    ...    ...  ...   ...   ...     ...    ...        ...
3655  1949     12   27    57    27    0.00    0.0          0
3656  1949     12   28    65    38    0.00    0.0          0
3657  1949     12   29    60    34    0.00    0.0          0
3658  1949     12   30    62    34    0.00    0.0          0
3659  1949     12   31    54    25    0.00    0.0          0

[3660 rows x 8 columns]

## HTML Table

In [8]:
df5 = pd.read_html('Data/boulderdaily_Part5.htm')[0]
df5

      year  month  day  tmax  tmin  precip   snow  snowcover
0     1950      1    1    59    35    0.00    0.0          0
1     1950      1    2    55    29    0.00    0.0          0
2     1950      1    3    32    -9    0.43    5.0          4
3     1950      1    4    16   -12    0.00    0.0          4
4     1950      1    5    30    -1    0.00    0.0          3
...    ...    ...  ...   ...   ...     ...    ...        ...
3655  1959     12   27    45    23    0.00    0.0          0
3656  1959     12   28    48    28    0.00    0.0          0
3657  1959     12   29    38    19    0.00    0.0          0
3658  1959     12   30    39    15    0.00    0.0          0
3659  1959     12   31    37    17 -999.00 -999.0          0

[3660 rows x 8 columns]

## Database

In [9]:
import sqlite3

connection = sqlite3.connect('Data/boulderdaily_Part6.sqlite')
cursor = connection.cursor()

query = '''SELECT name FROM sqlite_master  
WHERE type='table';'''

cursor.execute(query)
results = cursor.fetchall()
results

[('boulderdaily_Part6',)]

In [10]:
query = '''SELECT * 
FROM boulderdaily_Part6'''

cursor.execute(query)
results = cursor.fetchall()
results

[(1960, 1, 1, 31, 15, 0.07, 3.0, 2),
 (1960, 1, 2, 32, 4, 0.0, 0.0, 1),
 (1960, 1, 3, 24, 5, 0.0, 0.0, 1),
 (1960, 1, 4, 30, 3, 0.0, 0.0, 1),
 (1960, 1, 5, 36, 10, 0.0, 0.0, -999),
 (1960, 1, 6, 51, 18, 0.0, 0.0, -999),
 (1960, 1, 7, 54, 37, 0.0, 0.0, -999),
 (1960, 1, 8, 63, 25, 0.0, 0.0, 0),
 (1960, 1, 9, 65, 35, 0.0, 0.0, 0),
 (1960, 1, 10, 55, 32, 0.0, 0.0, 0),
 (1960, 1, 11, 53, 27, 0.0, 0.0, 0),
 (1960, 1, 12, 54, 31, 0.0, 0.0, 0),
 (1960, 1, 13, 50, 27, 0.0, 0.0, 0),
 (1960, 1, 14, 39, 21, 0.25, 3.5, 3),
 (1960, 1, 15, 34, 13, 0.0, 0.0, 3),
 (1960, 1, 16, 25, 14, 0.05, 2.0, 5),
 (1960, 1, 17, 23, 16, 0.16, 1.8, 7),
 (1960, 1, 18, 21, 4, 0.01, 0.1, 5),
 (1960, 1, 19, 30, -2, 0.0, 0.0, 4),
 (1960, 1, 20, 41, 4, 0.0, 0.0, 4),
 (1960, 1, 21, 32, 11, 0.0, 0.0, 4),
 (1960, 1, 22, 23, 4, 0.0, 0.0, 4),
 (1960, 1, 23, 47, 15, 0.0, 0.0, 4),
 (1960, 1, 24, 48, 19, 0.0, 0.0, 3),
 (1960, 1, 25, 48, 32, 0.0, 0.0, 3),
 (1960, 1, 26, 55, 29, 0.0, 0.0, 2),
 (1960, 1, 27, 54, 33, -999.0, -999.0, 1),
 (1960, 1, 28, 47, 32, 0.0, 0.0, 0),
 (1960, 1, 29, 61, 23, 0.0, 0.0, 0),
 (1960, 1, 30, 60, 33, 0.0, 0.0, 0),
 (1960, 1, 31, 48, 36, 0.0, 0.0, 0),
 (1960, 2, 1, 48, 30, 0.01, 0.1, -999),
 (1960, 2, 2, 40, 23, -998.0, -998.0, -999),
 (1960, 2, 3, 43, 31, 0.19, 1.5, -999),
 (1960, 2, 4, 46, 26, 0.0, 0.0, 0),
 (1960, 2, 5, 46, 26, 0.0, 0.0, 0),
 (1960, 2, 6, 52, 32, 0.0, 0.0, 0),
 (1960, 2, 7, 63, 26, 0.0, 0.0, 0),
 (1960, 2, 8, 59, 37, 0.0, 0.0, 0),
 (1960, 2, 9, 55, 37, 0.0, 0.0, 0),
 (1960, 2, 10, 42, 22, 0.0, 0.0, 0),
 (1960, 2, 11, 41, 26, 0.01, -999.0, -999),
 (1960, 2, 12, 49, 18, 0.02, 0.5, -999),
 (1960, 2, 13, 53, 30, 0.0, 0.0, -999),
 (1960, 2, 14, 45, 25, 0.25, 4.2, 4),
 (1960, 2, 15, 48, 22, 0.0, 0.0, 2),
 (1960, 2, 16, 41, 29, 0.0, 0.0, 1),
 (1960, 2, 17, 35, 21, 0.0, 0.0, -999),
 (1960, 2, 18, 35, 12, 0.0, 0.0, 0),
 (1960, 2, 19, 34, 17, 0.0, 0.0, 0),
 (1960, 2, 20, 33, 18, 0.06, 3.6, 2),
 (1960, 2, 21, 46, 17, 0.0, 0.0, 1),
 (1960, 2, 22, 39, 12, 0.3, 8.5, 9),
 (1960, 2, 23, 21, 1, 0.07, 1.0, 7),
 (1960, 2, 24, 21, 1, 0.0, 0.0, 6),
 (1960, 2, 25, 18, 1, -999.0, -999.0, 6),
 (1960, 2, 26, 14, 0, 0.03, 0.5, 6),
 (1960, 2, 27, 12, 1, 0.05, 0.6, 7),
 (1960, 2, 28, 12, -5, 0.01, 0.4, 7),
 (1960, 2, 29, 24, -5, 0.04, 0.5, 7),
 (1960, 3, 1, 17, 6, 0.01, 0.2, 7),
 (1960, 3, 2, 15, 3, 0.01, 2.0, 9),
 (1960, 3, 3, 42, -3, -999.0, -999.0, 8),
 (1960, 3, 4, 24, -1, -999.0, -999.0, 6),
 (1960, 3, 5, 42, 14, 0.0, 0.0, 5),
 (1960, 3, 6, 58, 24, 0.0, 0.0, 3),
 (1960, 3, 7, 50, 29, 0.0, 0.0, 2),
 (1960, 3, 8, 55, 30, 0.09, 0.0, 0),
 (1960, 3, 9, 53, 40, 0.0, 0.0, 0),
 (1960, 3, 10, 54, 29, -999.0, -999.0, 0),
 (1960, 3, 11, 47, 24, -999.0, -999.0, 0),
 (1960, 3, 12, 44, 24, 0.11, 1.0, 1),
 (1960, 3, 13, 27, 21, 0.11, 1.8, 3),
 (1960, 3, 14, 42, 18, 0.15, 1.5, 3),
 (1960, 3, 15, 39, 19, 0.22, 4.0, 4),
 (1960, 3, 16, 38, 24, -999.0, -999.0, 3),
 (1960, 3, 17, 47, 15, 0.0, 0.0, 2),
 (1960, 3, 18, 55, 38, 0.0, 0.0, 0),
 (1960, 3, 19, 64, 29, 0.0, 0.0, 0),
 (1960, 3, 20, 65, 35, 0.0, 0.0, 0),
 (1960, 3, 21, 70, 39, 0.0, 0.0, 0),
 (1960, 3, 22, 70, 37, 0.0, 0.0, 0),
 (1960, 3, 23, 65, 39, 0.0, 0.0, 0),
 (1960, 3, 24, 64, 34, 0.0, 0.0, 0),
 (1960, 3, 25, 70, 41, 0.0, 0.0, 0),
 (1960, 3, 26, 75, 45, 0.0, 0.0, 0),
 (1960, 3, 27, 73, 49, 0.0, 0.0, 0),
 (1960, 3, 28, 67, 49, -999.0, 0.0, 0),
 (1960, 3, 29, 57, 39, 0.0, 0.0, 0),
 (1960, 3, 30, 70, 39, 0.0, 0.0, 0),
 (1960, 3, 31, 66, 42, 0.02, 0.0, 0),
 (1960, 4, 1, 47, 31, 0.0, 0.0, 0),
 (1960, 4, 2, 54, 29, 0.0, 0.0, 0),
 (1960, 4, 3, 69, 35, 0.0, 0.0, 0),
 (1960, 4, 4, 65, 38, 0.0, 0.0, 0),
 (1960, 4, 5, 75, 38, 0.0, 0.0, 0),
 (1960, 4, 6, 74, 54, 0.0, 0.0, 0),
 (1960, 4, 7, 67, 43, -999.0, 0.0, 0),
 (1960, 4, 8, 60, 40, 0.28, 0.0, 0),
 (1960, 4, 9, 76, 42, 0.0, 0.0, 0),
 (1960, 4, 10, 80, 40, 0.0, 0.0, 0),
 (1960, 4, 11, 74, 44, 0.0, 0.0, 0),
 (1960, 4, 12, 61, 44, 0.11, 0.0, 0),
 (1960, 4, 13, 64, 37, -999.0, 0.0, 0),
 (1960, 4, 14, 74, 42, 0.0, 0.0, 0),
 (1960, 4, 15, 67, 41, 0.0, 0.0, 0),
 (1960, 4, 16, 60, 34, -999.0, -999.0, 0),
 (1960, 4, 17, 59, 26, 0.0, 0.0, 0),
 (1960, 4, 18, 76, 37, 0.0, 0.0, 0),
 (1960, 4, 19, 80, 47, 0.0, 0.0, 0),
 (1960, 4, 20, 76, 40, 0.0, 0.0, 0),
 (1960, 4, 21, 83, 51, 0.0, 0.0, 0),
 (1960, 4, 22, 81, 53, 0.0, 0.0, 0),
 (1960, 4, 23, 75, 46, 0.0, 0.0, 0),
 (1960, 4, 24, 69, 40, 0.18, -999.0, 0),
 (1960, 4, 25, 56, 30, 0.0, 0.0, 0),
 (1960, 4, 26, 58, 36, 0.0, 0.0, 0),
 (1960, 4, 27, 52, 37, 0.11, 0.0, 0),
 (1960, 4, 28, 47, 32, 0.27, -999.0, -999),
 (1960, 4, 29, 44, 30, 0.92, 7.3, 5),
 (1960, 4, 30, 50, 25, 0.03, 0.4, -999),
 (1960, 5, 1, 65, 37, 0.0, 0.0, 0),
 (1960, 5, 2, 69, 38, 0.0, 0.0, 0),
 (1960, 5, 3, 70, 45, -999.0, 0.0, 0),
 (1960, 5, 4, 67, 45, -999.0, 0.0, 0),
 (1960, 5, 5, 53, 37, 1.9, 0.0, 0),
 (1960, 5, 6, 61, 35, 0.1, 0.0, 0),
 (1960, 5, 7, 68, 39, 0.0, 0.0, 0),
 (1960, 5, 8, 74, 46, 0.0, 0.0, 0),
 (1960, 5, 9, 71, 44, 0.0, 0.0, 0),
 (1960, 5, 10, 76, 44, -999.0, 0.0, 0),
 (1960, 5, 11, 75, 47, 0.0, 0.0, 0),
 (1960, 5, 12, 87, 53, 0.0, 0.0, 0),
 (1960, 5, 13, 85, 65, 0.0, 0.0, 0),
 (1960, 5, 14, 83, 47, 0.0, 0.0, 0),
 (1960, 5, 15, 71, 46, -999.0, 0.0, 0),
 (1960, 5, 16, 70, 44, 0.02, 0.0, 0),
 (1960, 5, 17, 65, 49, 0.81, 0.0, 0),
 (1960, 5, 18, 64, 44, 0.14, 0.0, 0),
 (1960, 5, 19, 54, 32, 0.81, 1.5, 0),
 (1960, 5, 20, 68, 38, 0.0, 0.0, 0),
 (1960, 5, 21, 81, 42, 0.0, 0.0, 0),
 (1960, 5, 22, 82, 54, 0.0, 0.0, 0),
 (1960, 5, 23, 78, 48, -999.0, 0.0, 0),
 (1960, 5, 24, 75, 56, 0.01, 0.0, 0),
 (1960, 5, 25, 75, 45, 0.0, 0.0, 0),
 (1960, 5, 26, 77, 54, 0.0, 0.0, 0),
 (1960, 5, 27, 78, 51, 0.0, 0.0, 0),
 (1960, 5, 28, 74, 50, -999.0, 0.0, 0),
 (1960, 5, 29, 74, 51, -999.0, 0.0, 0),
 (1960, 5, 30, 82, 47, -999.0, 0.0, 0),
 (1960, 5, 31, 84, 62, 0.0, 0.0, 0),
 (1960, 6, 1, 81, 62, 0.0, 0.0, 0),
 (1960, 6, 2, 86, 61, 0.0, 0.0, 0),
 (1960, 6, 3, 90, 62, 0.0, 0.0, 0),
 (1960, 6, 4, 92, 66, 0.0, 0.0, 0),
 (1960, 6, 5, 80, 54, 0.54, 0.0, 0),
 (1960, 6, 6, 73, 53, 0.0, 0.0, 0),
 (1960, 6, 7, 76, 54, 0.0, 0.0, 0),
 (1960, 6, 8, 73, 53, 0.12, 0.0, 0),
 (1960, 6, 9, 78, 52, 0.02, 0.0, 0),
 (1960, 6, 10, 70, 51, 0.02, 0.0, 0),
 (1960, 6, 11, 73, 53, 0.14, 0.0, 0),
 (1960, 6, 12, 74, 53, 0.01, 0.0, 0),
 (1960, 6, 13, 79, 49, 0.0, 0.0, 0),
 (1960, 6, 14, 87, 57, 0.03, 0.0, 0),
 (1960, 6, 15, 80, 61, 0.0, 0.0, 0),
 (1960, 6, 16, 84, 50, 0.0, 0.0, 0),
 (1960, 6, 17, 94, 64, 0.0, 0.0, 0),
 (1960, 6, 18, 92, 61, 0.0, 0.0, 0),
 (1960, 6, 19, 92, 57, 0.0, 0.0, 0),
 (1960, 6, 20, 95, 62, 0.0, 0.0, 0),
 (1960, 6, 21, 92, 50, 0.0, 0.0, 0),
 (1960, 6, 22, 91, 47, 0.0, 0.0, 0),
 (1960, 6, 23, 88, 48, 0.0, 0.0, 0),
 (1960, 6, 24, 80, 50, 0.15, 0.0, 0),
 (1960, 6, 25, 91, 55, 0.0, 0.0, 0),
 (1960, 6, 26, 95, 68, 0.0, 0.0, 0),
 (1960, 6, 27, 92, 59, 0.0, 0.0, 0),
 (1960, 6, 28, 94, 62, 0.0, 0.0, 0),
 (1960, 6, 29, 95, 65, 0.0, 0.0, 0),
 (1960, 6, 30, 93, 62, 0.0, 0.0, 0),
 (1960, 7, 1, 91, 57, 0.0, 0.0, 0),
 (1960, 7, 2, 94, 70, -999.0, 0.0, 0),
 (1960, 7, 3, 83, 58, 0.2, 0.0, 0),
 (1960, 7, 4, 78, 53, 0.4, 0.0, 0),
 (1960, 7, 5, 73, 55, 0.04, 0.0, 0),
 (1960, 7, 6, 76, 55, 0.02, 0.0, 0),
 (1960, 7, 7, 73, 53, -999.0, 0.0, 0),
 (1960, 7, 8, 88, 56, -999.0, 0.0, 0),
 (1960, 7, 9, 92, 66, 0.0, 0.0, 0),
 (1960, 7, 10, 94, 65, 0.0, 0.0, 0),
 (1960, 7, 11, 86, 64, 0.04, 0.0, 0),
 (1960, 7, 12, 79, 62, 0.07, 0.0, 0),
 (1960, 7, 13, 79, 58, 0.01, 0.0, 0),
 (1960, 7, 14, 85, 54, -999.0, 0.0, 0),
 (1960, 7, 15, 88, 60, -999.0, 0.0, 0),
 (1960, 7, 16, 91, 64, -999.0, 0.0, 0),
 (1960, 7, 17, 86, 56, 0.01, 0.0, 0),
 (1960, 7, 18, 87, 62, 0.0, 0.0, 0),
 (1960, 7, 19, 92, 60, 0.0, 0.0, 0),
 (1960, 7, 20, 94, 63, 0.0, 0.0, 0),
 (1960, 7, 21, 91, 59, 0.0, 0.0, 0),
 (1960, 7, 22, 89, 72, 0.0, 0.0, 0),
 (1960, 7, 23, 91, 68, 0.0, 0.0, 0),
 (1960, 7, 24, 90, 61, 0.29, 0.0, 0),
 (1960, 7, 25, 91, 60, 0.0, 0.0, 0),
 (1960, 7, 26, 96, 71, 0.0, 0.0, 0),
 (1960, 7, 27, 95, 66, 0.0, 0.0, 0),
 (1960, 7, 28, 94, 70, 0.2, 0.0, 0),
 (1960, 7, 29, 92, 60, -999.0, 0.0, 0),
 (1960, 7, 30, 89, 62, -999.0, 0.0, 0),
 (1960, 7, 31, 93, 62, -999.0, 0.0, 0),
 (1960, 8, 1, 90, 64, 0.03, 0.0, 0),
 (1960, 8, 2, 93, 68, -999.0, 0.0, 0),
 (1960, 8, 3, 93, 67, 0.01, 0.0, 0),
 (1960, 8, 4, 95, 60, -999.0, 0.0, 0),
 (1960, 8, 5, 91, 66, 0.0, 0.0, 0),
 (1960, 8, 6, 96, 61, 0.01, 0.0, 0),
 (1960, 8, 7, 94, 61, 0.0, 0.0, 0),
 (1960, 8, 8, 85, 57, 0.0, 0.0, 0),
 (1960, 8, 9, 65, 53, 0.12, 0.0, 0),
 (1960, 8, 10, 78, 54, 0.07, 0.0, 0),
 (1960, 8, 11, 87, 58, -999.0, 0.0, 0),
 (1960, 8, 12, 92, 65, 0.0, 0.0, 0),
 (1960, 8, 13, 84, 65, 0.0, 0.0, 0),
 (1960, 8, 14, 87, 55, -999.0, 0.0, 0),
 (1960, 8, 15, 93, 55, 0.02, 0.0, 0),
 (1960, 8, 16, 91, 66, 0.01, 0.0, 0),
 (1960, 8, 17, 75, 49, -999.0, 0.0, 0),
 (1960, 8, 18, 80, 49, 0.0, 0.0, 0),
 (1960, 8, 19, 90, 53, 0.0, 0.0, 0),
 (1960, 8, 20, 92, 64, 0.0, 0.0, 0),
 (1960, 8, 21, 97, 62, 0.0, 0.0, 0),
 (1960, 8, 22, 94, 59, 0.0, 0.0, 0),
 (1960, 8, 23, 82, 67, 0.03, 0.0, 0),
 (1960, 8, 24, 82, 56, 0.11, 0.0, 0),
 (1960, 8, 25, 85, 54, -999.0, 0.0, 0),
 (1960, 8, 26, 89, 57, 0.0, 0.0, 0),
 (1960, 8, 27, 94, 64, 0.0, 0.0, 0),
 (1960, 8, 28, 86, 58, 0.0, 0.0, 0),
 (1960, 8, 29, 90, 51, 0.0, 0.0, 0),
 (1960, 8, 30, 93, 62, 0.0, 0.0, 0),
 (1960, 8, 31, 96, 60, 0.0, 0.0, 0),
 (1960, 9, 1, 95, 58, 0.0, 0.0, 0),
 (1960, 9, 2, 94, 62, 0.0, 0.0, 0),
 (1960, 9, 3, 94, 65, 0.11, 0.0, 0),
 (1960, 9, 4, 96, 66, 0.0, 0.0, 0),
 (1960, 9, 5, 93, 67, 0.0, 0.0, 0),
 (1960, 9, 6, 88, 66, -999.0, 0.0, 0),
 (1960, 9, 7, 86, 60, -999.0, 0.0, 0),
 (1960, 9, 8, 78, 55, -999.0, 0.0, 0),
 (1960, 9, 9, 63, 48, 0.22, 0.0, 0),
 (1960, 9, 10, 85, 44, 0.0, 0.0, 0),
 (1960, 9, 11, 78, 56, 0.0, 0.0, 0),
 (1960, 9, 12, 86, 46, 0.0, 0.0, 0),
 (1960, 9, 13, 79, 50, 0.0, 0.0, 0),
 (1960, 9, 14, 85, 55, -999.0, 0.0, 0),
 (1960, 9, 15, 75, 56, 0.06, 0.0, 0),
 (1960, 9, 16, 80, 46, 0.0, 0.0, 0),
 (1960, 9, 17, 72, 51, 0.08, 0.0, 0),
 (1960, 9, 18, 80, 49, 0.0, 0.0, 0),
 (1960, 9, 19, 84, 52, 0.0, 0.0, 0),
 (1960, 9, 20, 85, 51, 0.0, 0.0, 0),
 (1960, 9, 21, 76, 52, 0.0, 0.0, 0),
 (1960, 9, 22, 64, 44, 0.17, 0.0, 0),
 (1960, 9, 23, 70, 42, 0.02, 0.0, 0),
 (1960, 9, 24, 71, 42, 0.0, 0.0, 0),
 (1960, 9, 25, 84, 43, 0.0, 0.0, 0),
 (1960, 9, 26, 74, 50, 0.0, 0.0, 0),
 (1960, 9, 27, 78, 43, 0.01, 0.0, 0),
 (1960, 9, 28, 76, 60, -999.0, 0.0, 0),
 (1960, 9, 29, 71, 46, 0.0, 0.0, 0),
 (1960, 9, 30, 77, 38, 0.0, 0.0, 0),
 (1960, 10, 1, 79, 51, -999.0, 0.0, 0),
 (1960, 10, 2, 71, 44, 0.0, 0.0, 0),
 (1960, 10, 3, 76, 42, 0.0, 0.0, 0),
 (1960, 10, 4, 82, 48, 0.0, 0.0, 0),
 (1960, 10, 5, 80, 57, 0.0, 0.0, 0),
 (1960, 10, 6, 83, 55, 0.0, 0.0, 0),
 (1960, 10, 7, 84, 48, 0.0, 0.0, 0),
 (1960, 10, 8, 82, 47, 0.0, 0.0, 0),
 (1960, 10, 9, 69, 48, -999.0, 0.0, 0),
 (1960, 10, 10, 66, 41, 0.0, 0.0, 0),
 (1960, 10, 11, 70, 41, 0.0, 0.0, 0),
 (1960, 10, 12, 69, 43, 0.01, 0.0, 0),
 (1960, 10, 13, 66, 42, 0.0, 0.0, 0),
 (1960, 10, 14, 59, 34, 0.83, 0.0, 0),
 (1960, 10, 15, 46, 33, 0.41, 4.5, -999),
 (1960, 10, 16, 61, 33, 0.0, 0.0, 0),
 (1960, 10, 17, 55, 44, -999.0, -999.0, -999),
 (1960, 10, 18, 44, 35, 0.97, 0.0, 0),
 (1960, 10, 19, 51, 34, 0.15, 0.0, 0),
 (1960, 10, 20, 67, 35, 0.0, 0.0, 0),
 (1960, 10, 21, 73, 45, 0.0, 0.0, 0),
 (1960, 10, 22, 76, 45, 0.0, 0.0, 0),
 (1960, 10, 23, 72, 43, 0.0, 0.0, 0),
 (1960, 10, 24, 78, 40, 0.0, 0.0, 0),
 (1960, 10, 25, 64, 43, 0.0, 0.0, 0),
 (1960, 10, 26, 76, 34, 0.0, 0.0, 0),
 (1960, 10, 27, 77, 42, 0.0, 0.0, 0),
 (1960, 10, 28, 54, 36, 0.01, 0.0, 0),
 (1960, 10, 29, 52, 37, -999.0, -999.0, 0),
 (1960, 10, 30, 53, 28, 0.0, 0.0, 0),
 (1960, 10, 31, 62, 34, 0.0, 0.0, 0),
 (1960, 11, 1, 63, 43, -999.0, 0.0, 0),
 (1960, 11, 2, 60, 31, 0.0, 0.0, 0),
 (1960, 11, 3, 55, 32, -999.0, 0.0, 0),
 (1960, 11, 4, 44, 30, 0.02, -999.0, -999),
 (1960, 11, 5, 53, 29, 0.02, -999.0, -999),
 (1960, 11, 6, 54, 30, 0.0, 0.0, 0),
 (1960, 11, 7, 64, 30, 0.0, 0.0, 0),
 (1960, 11, 8, 52, 25, 0.1, 3.5, 3),
 (1960, 11, 9, 28, 20, 0.11, 1.5, 4),
 (1960, 11, 10, 52, 16, 0.0, 0.0, 2),
 (1960, 11, 11, 59, 31, 0.0, 0.0, -999),
 (1960, 11, 12, 63, 34, 0.0, 0.0, 0),
 (1960, 11, 13, 64, 30, 0.0, 0.0, 0),
 (1960, 11, 14, 62, 30, 0.0, 0.0, 0),
 (1960, 11, 15, 51, 34, 0.0, 0.0, 0),
 (1960, 11, 16, 62, 32, 0.0, 0.0, 0),
 (1960, 11, 17, 57, 33, 0.0, 0.0, 0),
 (1960, 11, 18, 67, 30, 0.0, 0.0, 0),
 (1960, 11, 19, 61, 35, 0.0, 0.0, 0),
 (1960, 11, 20, 64, 29, 0.0, 0.0, 0),
 (1960, 11, 21, 71, 34, 0.0, 0.0, 0),
 (1960, 11, 22, 56, 26, 0.0, 0.0, 0),
 (1960, 11, 23, 60, 22, 0.0, 0.0, 0),
 (1960, 11, 24, 64, 40, 0.0, 0.0, 0),
 (1960, 11, 25, 74, 44, 0.0, 0.0, 0),
 (1960, 11, 26, 72, 50, 0.0, 0.0, 0),
 (1960, 11, 27, 61, 23, -999.0, -999.0, -999),
 (1960, 11, 28, 45, 18, 0.02, 0.5, 0),
 (1960, 11, 29, 44, 15, 0.0, 0.0, 0),
 (1960, 11, 30, 45, 26, 0.0, 0.0, 0),
 (1960, 12, 1, 60, 22, 0.0, 0.0, 0),
 (1960, 12, 2, 69, 30, 0.0, 0.0, 0),
 (1960, 12, 3, 55, 34, 0.0, 0.0, 0),
 (1960, 12, 4, 45, 32, 0.46, 1.5, -999),
 (1960, 12, 5, 36, 18, 0.21, 6.0, 6),
 (1960, 12, 6, 28, 14, 0.28, 5.1, 7),
 (1960, 12, 7, 38, 8, 0.0, 0.0, 6),
 (1960, 12, 8, 37, 14, 0.0, 0.0, 5),
 (1960, 12, 9, 45, 13, 0.0, 0.0, 3),
 (1960, 12, 10, 43, 28, 0.01, 0.1, 3),
 (1960, 12, 11, 52, 27, 0.0, 0.0, 2),
 (1960, 12, 12, 47, 29, 0.0, 0.0, 2),
 (1960, 12, 13, 53, 24, 0.0, 0.0, 1),
 (1960, 12, 14, 58, 36, 0.0, 0.0, 1),
 (1960, 12, 15, 53, 21, 0.0, 0.0, 1),
 (1960, 12, 16, 42, 18, 0.0, 0.0, 1),
 (1960, 12, 17, 49, 20, 0.0, 0.0, 0),
 (1960, 12, 18, 52, 32, 0.0, 0.0, 0),
 (1960, 12, 19, 56, 34, 0.01, 0.1, -999),
 (1960, 12, 20, 40, 22, 0.0, 0.0, 0),
 (1960, 12, 21, 37, 21, 0.0, 0.0, 0),
 (1960, 12, 22, 41, 17, 0.02, 0.3, 0),
 (1960, 12, 23, 57, 31, 0.0, 0.0, 0),
 (1960, 12, 24, 64, 39, 0.0, 0.0, 0),
 (1960, 12, 25, 56, 38, 0.0, 0.0, 0),
 (1960, 12, 26, 46, 24, 0.0, 0.0, 0),
 (1960, 12, 27, 34, 21, 0.28, 4.5, 4),
 (1960, 12, 28, 32, 12, -999.0, 0.5, 4),
 (1960, 12, 29, 43, 11, 0.0, 0.0, 3),
 (1960, 12, 30, 54, 19, 0.0, 0.0, 2),
 (1960, 12, 31, 48, 19, 0.0, 0.0, 1),
 (1961, 1, 1, 46, 23, 0.0, 0.0, -999),
 (1961, 1, 2, 34, 12, 0.0, 0.0, -999),
 (1961, 1, 3, 43, 17, 0.0, 0.0, -999),
 (1961, 1, 4, 51, 19, 0.0, 0.0, -999),
 (1961, 1, 5, 51, 24, 0.0, 0.0, -999),
 (1961, 1, 6, 56, 27, 0.0, 0.0, 0),
 (1961, 1, 7, 48, 29, 0.0, 0.0, 0),
 (1961, 1, 8, 61, 23, 0.0, 0.0, 0),
 (1961, 1, 9, 62, 34, 0.0, 0.0, 0),
 (1961, 1, 10, 50, 35, 0.0, 0.0, 0),
 (1961, 1, 11, 55, 26, 0.0, 0.0, 0),
 (1961, 1, 12, 56, 28, 0.0, 0.0, 0),
 (1961, 1, 13, 45, 27, 0.0, 0.0, 0),
 (1961, 1, 14, 46, 26, 0.0, 0.0, 0),
 (1961, 1, 15, 58, 40, 0.0, 0.0, 0),
 (1961, 1, 16, 60, 38, 0.0, 0.0, 0),
 (1961, 1, 17, 57, 31, 0.0, 0.0, 0),
 (1961, 1, 18, 52, 28, 0.16, 3.0, 3),
 (1961, 1, 19, 45, 17, -999.0, 0.2, 1),
 (1961, 1, 20, 41, 20, 0.0, 0.0, -999),
 (1961, 1, 21, 57, 16, 0.0, 0.0, -999),
 (1961, 1, 22, 60, 37, 0.0, 0.0, 0),
 (1961, 1, 23, 70, 30, 0.0, 0.0, 0),
 (1961, 1, 24, 55, 22, 0.0, 0.0, 0),
 (1961, 1, 25, 30, 20, 0.04, 0.6, 1),
 (1961, 1, 26, 25, 10, 0.14, 4.9, 6),
 (1961, 1, 27, 28, -5, 0.09, 1.0, 5),
 (1961, 1, 28, 38, 11, 0.0, 0.0, 3),
 (1961, 1, 29, 50, 13, 0.0, 0.0, 3),
 (1961, 1, 30, 57, 25, 0.0, 0.0, 1),
 (1961, 1, 31, 64, 33, 0.0, 0.0, 1),
 (1961, 2, 1, 52, 32, 0.0, 0.0, 0),
 (1961, 2, 2, 53, 28, 0.0, 0.0, 0),
 (1961, 2, 3, 50, 26, 0.0, 0.0, 0),
 (1961, 2, 4, 40, 26, 0.0, 0.0, 0),
 (1961, 2, 5, 42, 22, -998.0, 0.0, 0),
 (1961, 2, 6, 45, 21, 0.0, 0.0, 0),
 (1961, 2, 7, 46, 19, 0.0, 0.0, 0),
 (1961, 2, 8, 51, 20, 0.0, 0.0, 0),
 (1961, 2, 9, 56, 26, 0.0, 0.0, 0),
 (1961, 2, 10, 65, 44, 0.0, 0.0, 0),
 (1961, 2, 11, 71, 48, 0.0, 0.0, 0),
 (1961, 2, 12, 67, 44, 0.0, 0.0, 0),
 (1961, 2, 13, 53, 30, 0.0, 0.0, 0),
 (1961, 2, 14, 60, 29, 0.0, 0.0, 0),
 (1961, 2, 15, 59, 28, 0.0, 0.0, 0),
 (1961, 2, 16, 62, 34, 0.0, 0.0, 0),
 (1961, 2, 17, 53, 23, 0.11, 1.3, 1),
 (1961, 2, 18, 25, 15, 0.08, 2.8, 3),
 (1961, 2, 19, 51, 15, 0.02, -999.0, 2),
 (1961, 2, 20, 52, 30, 0.0, 0.0, 0),
 (1961, 2, 21, 60, 35, 0.0, 0.0, 0),
 (1961, 2, 22, 61, 29, 0.0, 0.0, 0),
 (1961, 2, 23, 51, 25, 0.14, 1.5, 2),
 (1961, 2, 24, 51, 21, 0.0, 0.0, -999),
 (1961, 2, 25, 55, 40, 0.0, 0.0, -999),
 (1961, 2, 26, 46, 25, 0.29, 4.5, 4),
 (1961, 2, 27, 38, 17, 0.06, 0.5, 3),
 (1961, 2, 28, 44, 24, 0.0, 0.0, 2),
 (1961, 2, 29, -998, -998, -998.0, -998.0, -998),
 (1961, 3, 1, 57, 23, 0.0, 0.0, 0),
 (1961, 3, 2, 59, 44, 0.0, 0.0, 0),
 (1961, 3, 3, 46, 28, 0.68, 6.8, 5),
 (1961, 3, 4, 32, 24, 0.26, 3.4, 8),
 (1961, 3, 5, 32, 21, 0.12, 1.2, 7),
 (1961, 3, 6, 32, 10, -999.0, -999.0, 6),
 (1961, 3, 7, 42, 23, 0.0, 0.0, 5),
 (1961, 3, 8, 47, 23, 0.0, 0.0, 3),
 (1961, 3, 9, 50, 21, 0.0, 0.0, -999),
 (1961, 3, 10, 58, 34, 0.0, 0.0, 0),
 (1961, 3, 11, 55, 31, 0.0, 0.0, 0),
 (1961, 3, 12, 48, 31, -999.0, 0.0, 0),
 (1961, 3, 13, 66, 27, 0.0, 0.0, 0),
 (1961, 3, 14, 64, 34, 0.0, 0.0, 0),
 (1961, 3, 15, 69, 38, 0.0, 0.0, 0),
 (1961, 3, 16, 62, 37, 0.0, 0.0, 0),
 (1961, 3, 17, 53, 37, 0.09, 0.0, 0),
 (1961, 3, 18, 42, 30, 0.92, 9.5, 5),
 (1961, 3, 19, 40, 29, 0.15, 2.0, 3),
 (1961, 3, 20, 46, 25, 0.0, 0.0, 1),
 (1961, 3, 21, 52, 34, 0.0, 0.0, 0),
 (1961, 3, 22, 56, 28, 0.0, 0.0, 0),
 (1961, 3, 23, 65, 31, 0.0, 0.0, 0),
 (1961, 3, 24, 65, 30, -999.0, 0.0, 0),
 (1961, 3, 25, 63, 44, 0.0, 0.0, 0),
 (1961, 3, 26, 54, 35, 0.0, 0.0, 0),
 (1961, 3, 27, 45, 30, -999.0, -999.0, 0),
 (1961, 3, 28, 39, 23, 0.44, 7.2, 6),
 (1961, 3, 29, 37, 20, 0.02, 0.2, 3),
 (1961, 3, 30, 50, 21, 0.0, 0.0, -999),
 (1961, 3, 31, 54, 33, -999.0, 0.0, 0),
 (1961, 4, 1, 53, 38, -999.0, 0.0, 0),
 (1961, 4, 2, 65, 38, 0.0, 0.0, 0),
 (1961, 4, 3, 73, 40, 0.0, 0.0, 0),
 (1961, 4, 4, 69, 35, 0.07, 0.0, 0),
 (1961, 4, 5, 44, 25, 0.1, 2.5, -999),
 (1961, 4, 6, 40, 25, 0.1, 1.5, 1),
 (1961, 4, 7, 38, 28, -999.0, -999.0, -999),
 (1961, 4, 8, 43, 25, 0.05, 0.1, 0),
 (1961, 4, 9, 57, 24, 0.0, 0.0, 0),
 (1961, 4, 10, 51, 35, 0.1, 0.0, 0),
 (1961, 4, 11, 52, 32, 0.08, 0.0, 0),
 (1961, 4, 12, 67, 30, 0.0, 0.0, 0),
 (1961, 4, 13, 64, 44, 0.0, 0.0, 0),
 (1961, 4, 14, 53, 29, -999.0, -999.0, 0),
 (1961, 4, 15, 53, 19, 0.0, 0.0, 0),
 (1961, 4, 16, 55, 28, -999.0, -999.0, 0),
 (1961, 4, 17, 69, 36, 0.0, 0.0, 0),
 (1961, 4, 18, 77, 42, 0.0, 0.0, 0),
 (1961, 4, 19, 79, 53, 0.0, 0.0, 0),
 (1961, 4, 20, 72, 47, 0.0, 0.0, 0),
 (1961, 4, 21, 68, 39, 0.0, 0.0, 0),
 (1961, 4, 22, 77, 36, 0.0, 0.0, 0),
 (1961, 4, 23, 75, 45, 0.0, 0.0, 0),
 (1961, 4, 24, 57, 31, 0.23, 2.3, 2),
 (1961, 4, 25, 58, 26, -999.0, -999.0, 0),
 (1961, 4, 26, 59, 37, 0.0, 0.0, 0),
 (1961, 4, 27, 66, 31, 0.0, 0.0, 0),
 (1961, 4, 28, 70, 37, 0.0, 0.0, 0),
 (1961, 4, 29, 74, 41, 0.0, 0.0, 0),
 (1961, 4, 30, 76, 40, 0.0, 0.0, 0),
 (1961, 5, 1, 71, 42, 0.0, 0.0, 0),
 (1961, 5, 2, 77, 38, 0.0, 0.0, 0),
 (1961, 5, 3, 75, 43, 0.08, 0.0, 0),
 (1961, 5, 4, 62, 38, 0.2, 0.0, 0),
 (1961, 5, 5, 52, 39, 0.3, 0.0, 0),
 (1961, 5, 6, 64, 38, 0.0, 0.0, 0),
 (1961, 5, 7, 61, 41, 0.04, 0.0, 0),
 (1961, 5, 8, 63, 41, 0.01, 0.0, 0),
 (1961, 5, 9, 78, 46, 0.0, 0.0, 0),
 (1961, 5, 10, 87, 56, 0.0, 0.0, 0),
 (1961, 5, 11, 88, 52, 0.0, 0.0, 0),
 (1961, 5, 12, 84, 53, -999.0, 0.0, 0),
 (1961, 5, 13, 65, 35, 1.4, -999.0, 0),
 (1961, 5, 14, 64, 35, 0.18, 0.0, 0),
 (1961, 5, 15, 62, 43, 0.04, 0.0, 0),
 (1961, 5, 16, 64, 43, 0.04, 0.0, 0),
 (1961, 5, 17, 68, 39, 0.0, 0.0, 0),
 (1961, 5, 18, 71, 42, 0.0, 0.0, 0),
 (1961, 5, 19, 71, 48, 0.04, 0.0, 0),
 (1961, 5, 20, 66, 50, 0.2, 0.0, 0),
 (1961, 5, 21, 72, 49, 0.2, 0.0, 0),
 (1961, 5, 22, 65, 46, -999.0, 0.0, 0),
 (1961, 5, 23, 70, 46, 0.0, 0.0, 0),
 (1961, 5, 24, 76, 50, -999.0, 0.0, 0),
 (1961, 5, 25, 72, 48, 0.06, 0.0, 0),
 (1961, 5, 26, 72, 43, -999.0, 0.0, 0),
 (1961, 5, 27, 87, 57, -999.0, 0.0, 0),
 (1961, 5, 28, 82, 60, 0.0, 0.0, 0),
 (1961, 5, 29, 76, 56, 0.65, 0.0, 0),
 (1961, 5, 30, 77, 54, 0.02, 0.0, 0),
 (1961, 5, 31, 78, 57, 0.24, 0.0, 0),
 (1961, 6, 1, 77, 56, -999.0, 0.0, 0),
 (1961, 6, 2, 65, 53, 0.17, 0.0, 0),
 (1961, 6, 3, 62, 48, 0.31, 0.0, 0),
 (1961, 6, 4, 71, 44, -999.0, 0.0, 0),
 (1961, 6, 5, 75, 49, -999.0, 0.0, 0),
 (1961, 6, 6, 72, 49, 0.22, 0.0, 0),
 (1961, 6, 7, 76, 47, 0.11, 0.0, 0),
 (1961, 6, 8, 83, 51, 0.23, 0.0, 0),
 (1961, 6, 9, 85, 50, 0.0, 0.0, 0),
 (1961, 6, 10, 80, 61, 0.0, 0.0, 0),

In [11]:
df6 = pd.DataFrame(results)
df6

         0   1   2   3   4     5    6    7
0     1960   1   1  31  15  0.07  3.0    2
1     1960   1   2  32   4  0.00  0.0    1
2     1960   1   3  24   5  0.00  0.0    1
3     1960   1   4  30   3  0.00  0.0    1
4     1960   1   5  36  10  0.00  0.0 -999
...    ...  ..  ..  ..  ..   ...  ...  ...
7315  1979  12  27  35  29  0.96  9.5 -998
7316  1979  12  28  30  25  0.44  9.0 -998
7317  1979  12  29  32  15  0.00  0.0 -998
7318  1979  12  30  44  13  0.00  0.0 -998
7319  1979  12  31  52  16  0.00  0.0 -998

[7320 rows x 8 columns]

In [12]:
df6.columns = ['year',	'month',	'day',	'tmax',	'tmin',	'precip',	'snow',	'snowcover']
df6

      year  month  day  tmax  tmin  precip  snow  snowcover
0     1960      1    1    31    15    0.07   3.0          2
1     1960      1    2    32     4    0.00   0.0          1
2     1960      1    3    24     5    0.00   0.0          1
3     1960      1    4    30     3    0.00   0.0          1
4     1960      1    5    36    10    0.00   0.0       -999
...    ...    ...  ...   ...   ...     ...   ...        ...
7315  1979     12   27    35    29    0.96   9.5       -998
7316  1979     12   28    30    25    0.44   9.0       -998
7317  1979     12   29    32    15    0.00   0.0       -998
7318  1979     12   30    44    13    0.00   0.0       -998
7319  1979     12   31    52    16    0.00   0.0       -998

[7320 rows x 8 columns]

## XML

In [13]:
df7 = pd.read_xml('Data/boulderdaily_Part7.xml')
df7

      year  month  day  tmax  tmin  precip   snow  snowcover
0     1980      1    1    51    29     0.0    0.0       -998
1     1980      1    2    42    29  -999.0    0.0       -998
2     1980      1    3    43    14  -999.0    0.0       -998
3     1980      1    4    43    31     0.0    0.0       -998
4     1980      1    5    57    25     0.0    0.0       -998
...    ...    ...  ...   ...   ...     ...    ...        ...
7315  1999     12   27    54    29     0.0 -998.0       -998
7316  1999     12   28    63    32     0.0 -998.0       -998
7317  1999     12   29    63    30     0.0 -998.0       -998
7318  1999     12   30    58    27     0.0 -998.0       -998
7319  1999     12   31    60    26     0.0 -998.0       -998

[7320 rows x 8 columns]

## CSV

We have done this when we learned pandas. You can get the path of your csv file, and feed the path to the function `read_csv`.

In [14]:
df8 = pd.read_csv('Data/boulderdaily_Part8.csv')
df8

      year  month  day  tmax  tmin  precip   snow  snowcover
0     2000      1    1    54    29    0.00 -998.0       -998
1     2000      1    2    43    22    0.00 -998.0       -998
2     2000      1    3    36    19    0.08 -998.0       -998
3     2000      1    4    49    13    0.00 -998.0       -998
4     2000      1    5    47    26    0.00 -998.0       -998
...    ...    ...  ...   ...   ...     ...    ...        ...
8413  2022     12   27    62    32    0.00    0.0       -999
8414  2022     12   28    57    41 -999.00    0.0          0
8415  2022     12   29    41    21    1.26    9.3          9
8416  2022     12   30    37    19    0.00    0.0          8
8417  2022     12   31    53    23    0.00    0.0          6

[8418 rows x 8 columns]

## Integration!
Now we need to concatenate all dataframes together.

In [15]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8], ignore_index = True)
df

       year  month  day  tmax  tmin  precip   snow  snowcover
0      1897      1    1  -998  -998 -998.00 -998.0       -998
1      1897      1    2  -998  -998 -998.00 -998.0       -998
2      1897      1    3  -998  -998 -998.00 -998.0       -998
3      1897      1    4  -998  -998 -998.00 -998.0       -998
4      1897      1    5  -998  -998 -998.00 -998.0       -998
...     ...    ...  ...   ...   ...     ...    ...        ...
46111  2022     12   27    62    32    0.00    0.0       -999
46112  2022     12   28    57    41 -999.00    0.0          0
46113  2022     12   29    41    21    1.26    9.3          9
46114  2022     12   30    37    19    0.00    0.0          8
46115  2022     12   31    53    23    0.00    0.0          6

[46116 rows x 8 columns]

Now we save the integrated data

In [17]:
df.to_csv('Data/boulderdaily.csv', index = False)

test the data is successfully saved

In [18]:
test = pd.read_csv('Data/boulderdaily.csv')
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46116 entries, 0 to 46115
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   year       46116 non-null  int64
 1   month      46116 non-null  int64
 2   day        46116 non-null  int64
 3   tmax       46116 non-null  int64
 4   tmin       46116 non-null  int64
 5   precip     46116 non-null  float64
 6   snow       46116 non-null  float64
 7   snowcover  46116 non-null  int64
dtypes: float64(2), int64(6)
memory usage: 2.8 MB